### ISSUE TITLE
Improve performance by avoiding redundant Reflection

### ISSUE THREAD

**Issue by dymanoid** [pcfantasy/MoreEffectiveTransfer#1]
You're using Reflection each time to get values from private fields, e.g. [here](https://github.com/pcfantasy/MoreEffectiveTransfer/blob/1e6de11523fec32d1dacfa9f8973a594ffd275a3/CustomTransferManager.cs#L239).

Since this method is called on each simulation frame, you loose performance, because Reflection is slow.

Instead, consider a faster approach. At least, cache the `FieldInfo` instances. Prepare special delegates using `CreateDelegate`, or use e.g. [FastMember](https://github.com/mgravell/fast-member) to access the values.

**Comment by pcfantasy** [comment]
FastMember can only access public field I think, however I have fix the issue by other method.
https://github.com/pcfantasy/MoreEffectiveTransfer/commit/08c708a2e429f5e14fe951dfd04c2cad2e45fc7d
