### ISSUE TITLE
English wiki rework

### ISSUE THREAD

**Issue by AdmiralElectron** [pcfantasy/MoreEffectiveTransfer#16]
I reworked English wiki, just check it and update it.

I also suggest editing the name of 3rd advanced option to 'Reserve warehouse cargo trucks for local transfer' in the options menu. The current name is misleading as it suggests you are reserving cargo, not cargo trucks.

You can directly turn the .txt file in .md file by copy pasting, it's already formatted. I tried to commit directly, but couldn't do it.

[Moreeffectivetransfer_english_wiki_reworked.txt](https://github.com/pcfantasy/MoreEffectiveTransfer/files/4969531/Moreeffectivetransfer_english_wiki_reworked.txt)

**Comment by pcfantasy** [comment]
@quick20minadventure   Thanks, I will update this when I have time.

**Comment by pcfantasy** [comment]
@quick20minadventure   done, thanks again.

**Comment by pcfantasy** [comment]
https://github.com/pcfantasy/MoreEffectiveTransfer/commit/dec1953a12a69677c8be5c76cbdc8a605314d129
