### ISSUE TITLE
Spawn/Unspawn patch - Left-hand-traffic

### ISSUE THREAD

**Issue by WilliamDraco** [pcfantasy/MoreEffectiveTransfer#17]
This options to patch Spawn/Unspawn moves the points so that for right-hand-traffic (default) the spawn/despawn nodes are better. However, for left-hand-traffic these end up back-to-front.

Would you be able to swap the movements when the map is using left-hand-traffic?

**Comment by pcfantasy** [comment]
@WilliamDraco 

Thanks for mention this, I will try to fix this

**Comment by pcfantasy** [comment]
@WilliamDraco  fixed and update on steam, please test and give me feedback

**Comment by WilliamDraco** [comment]
Works as expected - Thank you very much!
