### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by thePapih** [pcfantasy/MoreEffectiveTransfer#18]
A Mod caused an error [System.Exception]

Details:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: An exception was thrown by the type initializer for CitiesHarmony.Installer ---> System.ArgumentException: You can only patch implemented methods/constructors. Path the declared method virtual UnityEngine.Color NetAI::GetColor(System.UInt16 nodeID, NetNode

**Comment by pcfantasy** [comment]
Please open an issue in  https://github.com/boformer/CitiesHarmony/issues

It is not my mod`s issue.
