### ISSUE TITLE
Wrong harmony usage

### ISSUE THREAD

**Issue by MacSergey** [pcfantasy/MoreEffectiveTransfer#19]
https://github.com/pcfantasy/MoreEffectiveTransfer/blob/0b9b00909656ddb957cf4720f29499ab705a8af8/Patch/WarehouseAICalculateSpawnPositionPatch.cs#L15
https://github.com/pcfantasy/MoreEffectiveTransfer/blob/0b9b00909656ddb957cf4720f29499ab705a8af8/Patch/WarehouseAICalculateUnSpawnPositionPatch.cs#L15

This patches is wrong. You patch virtual not declared methods, but you can patch only declared methods. It lead that other mods cant path this methods. You should change `typeof(WarehouseAI).GetMethod(...)` to `typeof(BuildingAI).GetMethod(...)`

**Comment by pcfantasy** [comment]
Seems you are right.

I will fix this when I have time to test, thanks a lot

**Comment by pcfantasy** [comment]
@MacSergey  @bloodypenguin

This will confict with https://github.com/bloodypenguin/Skylines-CargoFerries, right?

I will fix this if so.

**Comment by pcfantasy** [comment]
https://github.com/pcfantasy/MoreEffectiveTransfer/commit/2967095ba62646b69f285cd2233da1485553ef1e

fixed
