### ISSUE TITLE
(Strategy Nerd) RICO and some other buildings avoiding "further" connection opportunities

### ISSUE THREAD

**Issue by AsherWentworth** [pcfantasy/MoreEffectiveTransfer#2]
![Screenshot 33](https://user-images.githubusercontent.com/44278845/54795700-a9550b00-4c23-11e9-9e84-9beba2ada51d.png)
![Screenshot 34](https://user-images.githubusercontent.com/44278845/54795749-ce497e00-4c23-11e9-8ec1-ce810d0fd7dd.png)
![Screenshot 35](https://user-images.githubusercontent.com/44278845/54795779-e28d7b00-4c23-11e9-88fb-42113db00269.png)
![Screenshot 36](https://user-images.githubusercontent.com/44278845/54795823-fd5fef80-4c23-11e9-90e9-87782a4005dd.png)
![Screenshot 37](https://user-images.githubusercontent.com/44278845/54795851-18cafa80-4c24-11e9-9d18-c2b2bcc75afe.png)
![Screenshot 38](https://user-images.githubusercontent.com/44278845/54795873-3009e800-4c24-11e9-9ebf-1354e22d9a99.png)

Industrial buildings in my harbour seem to be refusing further connections and only accepting the one closest them, and while waiting for their ship to come in, (No pun intended) are complaining about not enough resources. The tanks not complaining are either new or Industries buildings, and the power stations seem to have no incoming routes. All RICO and industrial (Non-Industries DLC) buildings are only importing from the one harbour selected in green in screenshot 2. The last screenshot shows part of the route out; the Industries DLC buildings are all importing and exporting via that road.

**Comment by pcfantasy** [comment]
@AsherWentworth 

Thanks for the feedback.

I will update V2 version to steam, please try new version to see if still have this issue.

**Comment by pcfantasy** [comment]
@AsherWentworth 

New version is on steam now
