### ISSUE TITLE
License & continued development question

### ISSUE THREAD

**Issue by ghost** [pcfantasy/MoreEffectiveTransfer#20]
新年快乐!
Please excuse this way of contacting you, but I do not have any other email or qq of you.

You have done some very good work with the More Effective Transfer Manager (METM), and it is highly appreciated by lots of players, including me.
I am aware that you are from Mainland China and I do know about the current troubles with Steam and Steam Games in China.

To ensure a continued development of METM I want to ask you if you have any objections to me forking your code and continuing development for the Cities Skylines community, including publishing the mod on the Steam Workshop.

Since your code here on github does not specify a license (MIT, GPL, ...) I have to assume that it is "all rights reserved" by you.
So, in brief:
**1. Would you be OK if I continue development of this mod?**
**2. If yes, what would be your requisites?** I can contribute all my modifications as a pull request if you desire (be aware that my changes are quite extensive, as I intend to massively overhaul the core offer matching logic).
**3. Could you update your github repo with an appropriate license?** (e.g. a GPL license requires me to make all my derived work open source under GPL, too, so you can be sure that I cannot just take your code and not contribute back)

Thank you very much for your consideration, and enjoy the Chinese New Year!!

**Comment by pcfantasy** [comment]
add license for you and others.

https://github.com/pcfantasy/MoreEffectiveTransfer/blob/master/LICENSE
