### ISSUE TITLE
Mod causes an error just after loading

### ISSUE THREAD

**Issue by Prurite** [pcfantasy/MoreEffectiveTransfer#3]
I use it with Cities_Skylines from CODEX, with full DLC and 1.11.1-f4, and Network Extension 2 (no other mod). It caused an error when I start the game ( at the main page ), like below:
```
A Mod caused an error [ModException]

Details:
System.IndexOutOfRangeException: Array index is out of range.
  at OptionsMainPanel.AddUserMods () [0x00000] in <filename unknown>:0 
```

When I remove it from my mods folder everything just goes OK. Please help me find out what the problem is. Thanks.

**Comment by pcfantasy** [comment]
@Prurite 
send me output.log please

**Comment by Prurite** [comment]
Further test: Without NE2 ( load game only with this mod ), it's correctly loaded. Load it with NE2 : fails, output.log is here: [output_log.txt](https://github.com/pcfantasy/MoreEffectiveTransfer/files/3155282/output_log.txt) ( I find it under `Cities_Data` folder )

**Comment by pcfantasy** [comment]
@Prurite 

See blow: seems not bug with my mod.
https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Mods-missing-in-Content-Manager

**Comment by Prurite** [comment]
So what makes it incompatible with NE2?

**Comment by pcfantasy** [comment]
@Prurite  NE2 works fine with me,
