### ISSUE TITLE
Info request: disable export per transport and category

### ISSUE THREAD

**Issue by gab** [pcfantasy/MoreEffectiveTransfer#6]
Hi!

I'm looking into ways to disable export by truck, and/or completely disable export of certain categories of industrial products (helpful for Industries DLC production chains).

Have you identified where in the code this could be achieved? It seems it would be a matter of preventing external connections that have a road from generating export offers (are those called incoming or outgoing in the code?), or preventing all external connections from generating offers of a certain type e.g. livestock.

I intend to implement it myself if I have sufficient pointers.

Thank you.

**Comment by pcfantasy** [comment]
@gab 

patch  OutsideConnectionAI.AddConnectionOffers

if a outside building is itemClass type Road and it is incoming or incomingoutgoing, do not let this building send industrial products incoming offer.

**Comment by gab** [comment]
Thanks a lot for the info!
